---

- name: Ensure AWS alias name
  aws_alias:
    aws_account_alias: "{{ aws_account_alias }}"
    aws_account_state: "{{ aws_account_state }}"
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
  register: aws_alias_status
  check_mode: no
